// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Mymarket.Infrastructure.Data;

#nullable disable

namespace Mymarket.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519120000_AddUserBlockingAndUserPermissions")]
    partial class AddUserBlockingAndUserPermissions
    {
    }
}
