//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mymarket.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mymarket.Application.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute with this code already exists.
        /// </summary>
        public static string AttributeCodeExists {
            get {
                return ResourceManager.GetString("AttributeCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute code must not exceed 255 charactes.
        /// </summary>
        public static string AttributeCodeLength {
            get {
                return ResourceManager.GetString("AttributeCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute code is required.
        /// </summary>
        public static string AttributeCodeRequired {
            get {
                return ResourceManager.GetString("AttributeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attribute type.
        /// </summary>
        public static string AttributeTypeInvalid {
            get {
                return ResourceManager.GetString("AttributeTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute type is required.
        /// </summary>
        public static string AttributeTypeRequired {
            get {
                return ResourceManager.GetString("AttributeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code have already sent.
        /// </summary>
        public static string CodeAlreadySent {
            get {
                return ResourceManager.GetString("CodeAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired code.
        /// </summary>
        public static string CodeInvalidOrExpired {
            get {
                return ResourceManager.GetString("CodeInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time code must contain 6 symbols.
        /// </summary>
        public static string CodeLength {
            get {
                return ResourceManager.GetString("CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find code.
        /// </summary>
        public static string CodeNotFound {
            get {
                return ResourceManager.GetString("CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like this email is already registered.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already verified.
        /// </summary>
        public static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not exceed 255 characters.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify email first.
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string EmailOrPhoneRequired {
            get {
                return ResourceManager.GetString("EmailOrPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired.
        /// </summary>
        public static string InvalidRefreshOrUser {
            get {
                return ResourceManager.GetString("InvalidRefreshOrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label length must not exceed 255 characters.
        /// </summary>
        public static string LabelLength {
            get {
                return ResourceManager.GetString("LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label is requied.
        /// </summary>
        public static string LabelRequired {
            get {
                return ResourceManager.GetString("LabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must not exceed 72 characters.
        /// </summary>
        public static string LastnameMaxLength {
            get {
                return ResourceManager.GetString("LastnameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must contain only letters.
        /// </summary>
        public static string LastnameOnlyLetters {
            get {
                return ResourceManager.GetString("LastnameOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastnameRequired {
            get {
                return ResourceManager.GetString("LastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must not exceed 72 characters.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must only contain letters.
        /// </summary>
        public static string NameOnlyLetters {
            get {
                return ResourceManager.GetString("NameOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string PasswordDoesnotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesnotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 64 characters.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain spaces.
        /// </summary>
        public static string PasswordNoSpaces {
            get {
                return ResourceManager.GetString("PasswordNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number.
        /// </summary>
        public static string PasswordNumber {
            get {
                return ResourceManager.GetString("PasswordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character.
        /// </summary>
        public static string PasswordSpecial {
            get {
                return ResourceManager.GetString("PasswordSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter.
        /// </summary>
        public static string PasswordUppercase {
            get {
                return ResourceManager.GetString("PasswordUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must not exceed 18 characters.
        /// </summary>
        public static string PhoneMaxLength {
            get {
                return ResourceManager.GetString("PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string PhoneMinLength {
            get {
                return ResourceManager.GetString("PhoneMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like this phone number is already in use.
        /// </summary>
        public static string PhoneNumberAlreadyExists {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit must not exceed 255 characters.
        /// </summary>
        public static string UnitLength {
            get {
                return ResourceManager.GetString("UnitLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email does not exist.
        /// </summary>
        public static string UserWithEmailDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithEmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is required.
        /// </summary>
        public static string VerificationCodeRequired {
            get {
                return ResourceManager.GetString("VerificationCodeRequired", resourceCulture);
            }
        }
    }
}
